#!/bin/sh
chown -R www-data:www-data .

find . -type f -exec chmod 664 {} \;
find ./bin -type f -exec chmod 775 {} \;
find . -type d -exec chmod 775 {} \;
find . -type d -exec chmod +s {} \;
chmod -R g+rwX .
chmod o+x permissions
